-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.12-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             8.2.0.4675
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for locadora
CREATE DATABASE IF NOT EXISTS `locadora` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `locadora`;


-- Dumping structure for table locadora.categoria_midia
CREATE TABLE IF NOT EXISTS `categoria_midia` (
  `CATEGORIA_MIDIA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORIA_MIDIA_DESCRICAO` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`CATEGORIA_MIDIA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.classificacao
CREATE TABLE IF NOT EXISTS `classificacao` (
  `CLASSIFICACAO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `CLASSIFICACAO_DESCRICAO` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`CLASSIFICACAO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.cliente
CREATE TABLE IF NOT EXISTS `cliente` (
  `CLIENTE_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `CLIENTE_NOME` varchar(35) DEFAULT NULL,
  `CLIENTE_RG` int(11) DEFAULT NULL,
  `CLIENTE_CPF` int(11) DEFAULT NULL,
  `CLIENTE_ENDERECO` varchar(100) DEFAULT NULL,
  `CLIENTE_BAIRRO` varchar(100) DEFAULT NULL,
  `CLIENTE_CIDADE` varchar(100) DEFAULT NULL,
  `CLIENTE_ESTADO` varchar(100) DEFAULT NULL,
  `CLIENTE_TELEFONE` int(11) DEFAULT NULL,
  `CLIENTE_EMAIL` blob,
  `CLIENTE_NOME_MAE` int(11) DEFAULT NULL,
  `CLIENTE_NOME_PAI` varchar(55) DEFAULT NULL,
  `CLIENTE_DEPENDENTES` int(11) DEFAULT NULL,
  `EMPRESA_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`CLIENTE_CODIGO`),
  KEY `FK_EMPRESA_CODIGO` (`EMPRESA_CODIGO`),
  CONSTRAINT `FK_EMPRESA_CODIGO` FOREIGN KEY (`EMPRESA_CODIGO`) REFERENCES `empresa` (`EMPRESA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.dependentes
CREATE TABLE IF NOT EXISTS `dependentes` (
  `DEPENDENTES_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DEPENDENTES_DESCRICAO` varchar(50) DEFAULT NULL,
  `CLIENTE_CODIGO` int(11) DEFAULT NULL,
  PRIMARY KEY (`DEPENDENTES_CODIGO`),
  KEY `FK_CLIENTE_CODIGO` (`CLIENTE_CODIGO`),
  CONSTRAINT `FK_CLIENTE_CODIGO` FOREIGN KEY (`CLIENTE_CODIGO`) REFERENCES `cliente` (`CLIENTE_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.descarte
CREATE TABLE IF NOT EXISTS `descarte` (
  `DESCARTE_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DESCARTE_MOTIVO` varchar(100) DEFAULT NULL,
  `MIDIA_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`DESCARTE_CODIGO`),
  KEY `FK_MIDIAS_CODIGO` (`MIDIA_CODIGO`),
  CONSTRAINT `FK_MIDIAS_CODIGO` FOREIGN KEY (`MIDIA_CODIGO`) REFERENCES `midias` (`MIDIAS_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.devolucao
CREATE TABLE IF NOT EXISTS `devolucao` (
  `DEVOLUCAO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DEVOLUCAO_DESCRICAO` varchar(50) DEFAULT NULL,
  `CLIENTE_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`DEVOLUCAO_CODIGO`),
  KEY `FK_DEVOLUCAO_CLIENTE_CODIGO` (`CLIENTE_CODIGO`),
  CONSTRAINT `FK_DEVOLUCAO_CLIENTE_CODIGO` FOREIGN KEY (`CLIENTE_CODIGO`) REFERENCES `cliente` (`CLIENTE_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.empresa
CREATE TABLE IF NOT EXISTS `empresa` (
  `EMPRESA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `EMPRESA_NOME_FANTASIA` varchar(40) DEFAULT NULL,
  `EMPRESA_RAZAO_SOCIAL` varchar(40) DEFAULT NULL,
  `EMPRESA_CNPJ` varchar(18) DEFAULT NULL,
  PRIMARY KEY (`EMPRESA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.emprestimo
CREATE TABLE IF NOT EXISTS `emprestimo` (
  `EMPRESTIMO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `EMPRESTIMO_DATA` date DEFAULT NULL,
  `CLIENTE_CODIGO` int(11) DEFAULT NULL,
  `CLIENTE_DEPENDENTE` char(1) DEFAULT NULL,
  `CODIGO_DEPENDENTE` int(11) DEFAULT NULL,
  `FUNCIONARIO_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`EMPRESTIMO_CODIGO`),
  KEY `FK_FUNCIONARIO_CODIGO` (`FUNCIONARIO_CODIGO`),
  KEY `FK_EMPRESTIMO_CLIENTE_CODIGO` (`CLIENTE_CODIGO`),
  KEY `FK_EMPRESTIMO_DEPENDENTE_CODIGO` (`CODIGO_DEPENDENTE`),
  CONSTRAINT `FK_EMPRESTIMO_CLIENTE_CODIGO` FOREIGN KEY (`CLIENTE_CODIGO`) REFERENCES `cliente` (`CLIENTE_CODIGO`),
  CONSTRAINT `FK_EMPRESTIMO_DEPENDENTE_CODIGO` FOREIGN KEY (`CODIGO_DEPENDENTE`) REFERENCES `dependentes` (`DEPENDENTES_CODIGO`),
  CONSTRAINT `FK_FUNCIONARIO_CODIGO` FOREIGN KEY (`FUNCIONARIO_CODIGO`) REFERENCES `funcionario` (`FUNCIONARIO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.emprestimo_itens
CREATE TABLE IF NOT EXISTS `emprestimo_itens` (
  `EMPRESTIMO_ITENS_CODIGO` int(11) NOT NULL,
  `MIDIA_CODIGO` int(11) DEFAULT NULL,
  `EMPRESTIMO_CODIGO` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPRESTIMO_ITENS_CODIGO`),
  KEY `FK_EMPRESTIMO_ITENS_EMPRESTIMO_CODIGO` (`EMPRESTIMO_CODIGO`),
  CONSTRAINT `FK_EMPRESTIMO_ITENS_EMPRESTIMO_CODIGO` FOREIGN KEY (`EMPRESTIMO_CODIGO`) REFERENCES `emprestimo` (`EMPRESTIMO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- Data exporting was unselected.


-- Dumping structure for table locadora.funcionario
CREATE TABLE IF NOT EXISTS `funcionario` (
  `FUNCIONARIO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_NOME` varchar(40) DEFAULT NULL,
  `FUNCIONARIO_DATAADMISSAO` date DEFAULT NULL,
  `FUNCIONARIO_CPF` varchar(12) DEFAULT NULL,
  `FUNCIONARIO_LOGIN` varchar(15) DEFAULT NULL,
  `FUNCIONARIO_SENHA` varchar(15) DEFAULT NULL,
  `EMPRESA_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_CODIGO`),
  KEY `FK_FUNCIONARIO_EMPRESA_CODIGO` (`EMPRESA_CODIGO`),
  CONSTRAINT `FK_FUNCIONARIO_EMPRESA_CODIGO` FOREIGN KEY (`EMPRESA_CODIGO`) REFERENCES `empresa` (`EMPRESA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.genero
CREATE TABLE IF NOT EXISTS `genero` (
  `GENERO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `GENERO_DECRICAO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`GENERO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.itens_midia
CREATE TABLE IF NOT EXISTS `itens_midia` (
  `ITENS_MIDIA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `ITENS_MIDIA_DESCRICAO` varchar(50) DEFAULT NULL,
  `EMPRESTIMO_CODIGO` int(11) NOT NULL,
  `MIDIAS_CODIGO` int(11) NOT NULL,
  `DESCARTE_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`ITENS_MIDIA_CODIGO`),
  KEY `FK_EMPRESTIMO_CODIGO` (`EMPRESTIMO_CODIGO`),
  KEY `FK_ITENS_MIDIA_MIDIAS_CODIGO` (`MIDIAS_CODIGO`),
  KEY `FK_ITENS_MIDIA_DESCARTE_CODIGO` (`DESCARTE_CODIGO`),
  CONSTRAINT `FK_EMPRESTIMO_CODIGO` FOREIGN KEY (`EMPRESTIMO_CODIGO`) REFERENCES `emprestimo` (`EMPRESTIMO_CODIGO`),
  CONSTRAINT `FK_ITENS_MIDIA_DESCARTE_CODIGO` FOREIGN KEY (`DESCARTE_CODIGO`) REFERENCES `descarte` (`DESCARTE_CODIGO`),
  CONSTRAINT `FK_ITENS_MIDIA_MIDIAS_CODIGO` FOREIGN KEY (`MIDIAS_CODIGO`) REFERENCES `midias` (`MIDIAS_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.midias
CREATE TABLE IF NOT EXISTS `midias` (
  `MIDIAS_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `MIDIAS_NOME` varchar(40) DEFAULT NULL,
  `MIDIAS_DIRETOR` varchar(40) DEFAULT NULL,
  `MIDIAS_ATORES` blob,
  `MIDIAS_SINOPSE` blob,
  `MIDIAS_IMAGENS` int(11) DEFAULT NULL,
  `MIDIAS_ANO_LANCAMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `GENERO_CODIGO` int(11) NOT NULL,
  `CLASSIFICACAO_CODIGO` int(11) NOT NULL,
  `CATEGORIA_MIDIA_CODIGO` int(11) NOT NULL,
  `MIDIA_COPIAS` int(11) DEFAULT NULL,
  PRIMARY KEY (`MIDIAS_CODIGO`),
  KEY `FK_GENERO_CODIGO` (`GENERO_CODIGO`),
  KEY `FK_CLASSIFICACAO_CODIGO` (`CLASSIFICACAO_CODIGO`),
  KEY `FK_CATEGORIA_MIDIA_CODIGO` (`CATEGORIA_MIDIA_CODIGO`),
  CONSTRAINT `FK_CATEGORIA_MIDIA_CODIGO` FOREIGN KEY (`CATEGORIA_MIDIA_CODIGO`) REFERENCES `categoria_midia` (`CATEGORIA_MIDIA_CODIGO`),
  CONSTRAINT `FK_CLASSIFICACAO_CODIGO` FOREIGN KEY (`CLASSIFICACAO_CODIGO`) REFERENCES `classificacao` (`CLASSIFICACAO_CODIGO`),
  CONSTRAINT `FK_GENERO_CODIGO` FOREIGN KEY (`GENERO_CODIGO`) REFERENCES `genero` (`GENERO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.movimentacao
CREATE TABLE IF NOT EXISTS `movimentacao` (
  `MOVIMENTACAO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `MOVIMENTACAO_DESCRICAO` varchar(255) DEFAULT NULL,
  `FUNCIONARIO_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`MOVIMENTACAO_CODIGO`),
  KEY `FK_MOVIMENTACAO_FUNCIONARIO_CODIGO` (`FUNCIONARIO_CODIGO`),
  CONSTRAINT `FK_MOVIMENTACAO_FUNCIONARIO_CODIGO` FOREIGN KEY (`FUNCIONARIO_CODIGO`) REFERENCES `funcionario` (`FUNCIONARIO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table locadora.tipo_midia
CREATE TABLE IF NOT EXISTS `tipo_midia` (
  `TIPO_MIDIA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_MIDIA_VALOR` decimal(10,2) DEFAULT NULL,
  `TIPO_MIDIA_QTD_DIAS` int(11) DEFAULT NULL,
  `CATEGORIA_MIDIA_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`TIPO_MIDIA_CODIGO`),
  KEY `FK_TIPO_MIDIA_CATEGORIA_MIDIA_CODIGO` (`CATEGORIA_MIDIA_CODIGO`),
  CONSTRAINT `FK_TIPO_MIDIA_CATEGORIA_MIDIA_CODIGO` FOREIGN KEY (`CATEGORIA_MIDIA_CODIGO`) REFERENCES `categoria_midia` (`CATEGORIA_MIDIA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
