-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.12-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             8.2.0.4675
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for locadora
CREATE DATABASE IF NOT EXISTS `locadora` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `locadora`;


-- Dumping structure for table locadora.categoria_midia
CREATE TABLE IF NOT EXISTS `categoria_midia` (
  `CATEGORIA_MIDIA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORIA_MIDIA_DESCRICAO` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`CATEGORIA_MIDIA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.categoria_midia: ~0 rows (approximately)
/*!40000 ALTER TABLE `categoria_midia` DISABLE KEYS */;
/*!40000 ALTER TABLE `categoria_midia` ENABLE KEYS */;


-- Dumping structure for table locadora.classificacao
CREATE TABLE IF NOT EXISTS `classificacao` (
  `CLASSIFICACAO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `CLASSIFICACAO_DESCRICAO` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`CLASSIFICACAO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.classificacao: ~0 rows (approximately)
/*!40000 ALTER TABLE `classificacao` DISABLE KEYS */;
/*!40000 ALTER TABLE `classificacao` ENABLE KEYS */;


-- Dumping structure for table locadora.cliente
CREATE TABLE IF NOT EXISTS `cliente` (
  `CLIENTE_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `CLIENTE_NOME` varchar(55) DEFAULT NULL,
  `CLIENTE_RG` int(11) DEFAULT NULL,
  `CLIENTE_CPF` varchar(14) DEFAULT NULL,
  `CLIENTE_DATA_NASCIMENTO` date DEFAULT NULL,
  `CLIENTE_ENDERECO` varchar(100) DEFAULT NULL,
  `CLIENTE_BAIRRO` varchar(100) DEFAULT NULL,
  `CLIENTE_CIDADE` varchar(100) DEFAULT NULL,
  `CLIENTE_ESTADO` varchar(100) DEFAULT NULL,
  `CLIENTE_TELEFONE` char(15) DEFAULT NULL,
  `CLIENTE_EMAIL` blob,
  `CLIENTE_NOME_MAE` varchar(55) DEFAULT NULL,
  `CLIENTE_NOME_PAI` varchar(55) DEFAULT NULL,
  `CLIENTE_DEPENDENTES` int(11) DEFAULT NULL,
  PRIMARY KEY (`CLIENTE_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.cliente: ~0 rows (approximately)
/*!40000 ALTER TABLE `cliente` DISABLE KEYS */;
INSERT INTO `cliente` (`CLIENTE_CODIGO`, `CLIENTE_NOME`, `CLIENTE_RG`, `CLIENTE_CPF`, `CLIENTE_DATA_NASCIMENTO`, `CLIENTE_ENDERECO`, `CLIENTE_BAIRRO`, `CLIENTE_CIDADE`, `CLIENTE_ESTADO`, `CLIENTE_TELEFONE`, `CLIENTE_EMAIL`, `CLIENTE_NOME_MAE`, `CLIENTE_NOME_PAI`, `CLIENTE_DEPENDENTES`) VALUES
	(5, 'Guilherme Fernandes Campos', 654654654, '465.423.131-31', '2014-12-31', 'Rua Júlio Martinez Benevides,', 'kjhfkjf', 'Tangara da serra', 'MT', '(65) 9642-1662', _binary 0x67756963616D706F7374676140676D61696C2E636F6D, 'hgfjhghk', 'khgfkhgfk', 1);
/*!40000 ALTER TABLE `cliente` ENABLE KEYS */;


-- Dumping structure for table locadora.dependentes
CREATE TABLE IF NOT EXISTS `dependentes` (
  `DEPENDENTES_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DEPENDENTES_DESCRICAO` varchar(50) DEFAULT NULL,
  `CLIENTE_CODIGO` int(11) DEFAULT NULL,
  PRIMARY KEY (`DEPENDENTES_CODIGO`),
  KEY `FK_CLIENTE_CODIGO` (`CLIENTE_CODIGO`),
  CONSTRAINT `FK_CLIENTE_CODIGO` FOREIGN KEY (`CLIENTE_CODIGO`) REFERENCES `cliente` (`CLIENTE_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.dependentes: ~1 rows (approximately)
/*!40000 ALTER TABLE `dependentes` DISABLE KEYS */;
INSERT INTO `dependentes` (`DEPENDENTES_CODIGO`, `DEPENDENTES_DESCRICAO`, `CLIENTE_CODIGO`) VALUES
	(1, 'dfsdg', NULL);
/*!40000 ALTER TABLE `dependentes` ENABLE KEYS */;


-- Dumping structure for table locadora.descarte
CREATE TABLE IF NOT EXISTS `descarte` (
  `DESCARTE_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DESCARTE_MOTIVO` varchar(100) DEFAULT NULL,
  `MIDIA_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`DESCARTE_CODIGO`),
  KEY `FK_MIDIAS_CODIGO` (`MIDIA_CODIGO`),
  CONSTRAINT `FK_MIDIAS_CODIGO` FOREIGN KEY (`MIDIA_CODIGO`) REFERENCES `midias` (`MIDIAS_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.descarte: ~0 rows (approximately)
/*!40000 ALTER TABLE `descarte` DISABLE KEYS */;
/*!40000 ALTER TABLE `descarte` ENABLE KEYS */;


-- Dumping structure for table locadora.devolucao
CREATE TABLE IF NOT EXISTS `devolucao` (
  `DEVOLUCAO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DEVOLUCAO_DESCRICAO` varchar(50) DEFAULT NULL,
  `CLIENTE_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`DEVOLUCAO_CODIGO`),
  KEY `FK_DEVOLUCAO_CLIENTE_CODIGO` (`CLIENTE_CODIGO`),
  CONSTRAINT `FK_DEVOLUCAO_CLIENTE_CODIGO` FOREIGN KEY (`CLIENTE_CODIGO`) REFERENCES `cliente` (`CLIENTE_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.devolucao: ~0 rows (approximately)
/*!40000 ALTER TABLE `devolucao` DISABLE KEYS */;
/*!40000 ALTER TABLE `devolucao` ENABLE KEYS */;


-- Dumping structure for table locadora.empresa
CREATE TABLE IF NOT EXISTS `empresa` (
  `EMPRESA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `EMPRESA_NOME_FANTASIA` varchar(40) DEFAULT NULL,
  `EMPRESA_RAZAO_SOCIAL` varchar(40) DEFAULT NULL,
  `EMPRESA_CNPJ` varchar(18) DEFAULT NULL,
  PRIMARY KEY (`EMPRESA_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.empresa: ~1 rows (approximately)
/*!40000 ALTER TABLE `empresa` DISABLE KEYS */;
INSERT INTO `empresa` (`EMPRESA_CODIGO`, `EMPRESA_NOME_FANTASIA`, `EMPRESA_RAZAO_SOCIAL`, `EMPRESA_CNPJ`) VALUES
	(1, 'ghjghj', 'gjghj', '123456789101112');
/*!40000 ALTER TABLE `empresa` ENABLE KEYS */;


-- Dumping structure for table locadora.emprestimo
CREATE TABLE IF NOT EXISTS `emprestimo` (
  `EMPRESTIMO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `EMPRESTIMO_DATA` date DEFAULT NULL,
  `CLIENTE_CODIGO` int(11) DEFAULT NULL,
  `CLIENTE_DEPENDENTE` char(1) DEFAULT NULL,
  `CODIGO_DEPENDENTE` int(11) DEFAULT NULL,
  `FUNCIONARIO_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`EMPRESTIMO_CODIGO`),
  KEY `FK_FUNCIONARIO_CODIGO` (`FUNCIONARIO_CODIGO`),
  KEY `FK_EMPRESTIMO_CLIENTE_CODIGO` (`CLIENTE_CODIGO`),
  KEY `FK_EMPRESTIMO_DEPENDENTE_CODIGO` (`CODIGO_DEPENDENTE`),
  CONSTRAINT `FK_EMPRESTIMO_CLIENTE_CODIGO` FOREIGN KEY (`CLIENTE_CODIGO`) REFERENCES `cliente` (`CLIENTE_CODIGO`),
  CONSTRAINT `FK_EMPRESTIMO_DEPENDENTE_CODIGO` FOREIGN KEY (`CODIGO_DEPENDENTE`) REFERENCES `dependentes` (`DEPENDENTES_CODIGO`),
  CONSTRAINT `FK_FUNCIONARIO_CODIGO` FOREIGN KEY (`FUNCIONARIO_CODIGO`) REFERENCES `funcionario` (`FUNCIONARIO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.emprestimo: ~0 rows (approximately)
/*!40000 ALTER TABLE `emprestimo` DISABLE KEYS */;
/*!40000 ALTER TABLE `emprestimo` ENABLE KEYS */;


-- Dumping structure for table locadora.emprestimo_itens
CREATE TABLE IF NOT EXISTS `emprestimo_itens` (
  `EMPRESTIMO_ITENS_CODIGO` int(11) NOT NULL,
  `MIDIA_CODIGO` int(11) DEFAULT NULL,
  `EMPRESTIMO_CODIGO` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPRESTIMO_ITENS_CODIGO`),
  KEY `FK_EMPRESTIMO_ITENS_EMPRESTIMO_CODIGO` (`EMPRESTIMO_CODIGO`),
  CONSTRAINT `FK_EMPRESTIMO_ITENS_EMPRESTIMO_CODIGO` FOREIGN KEY (`EMPRESTIMO_CODIGO`) REFERENCES `emprestimo` (`EMPRESTIMO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- Dumping data for table locadora.emprestimo_itens: ~0 rows (approximately)
/*!40000 ALTER TABLE `emprestimo_itens` DISABLE KEYS */;
/*!40000 ALTER TABLE `emprestimo_itens` ENABLE KEYS */;


-- Dumping structure for table locadora.funcionario
CREATE TABLE IF NOT EXISTS `funcionario` (
  `FUNCIONARIO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_NOME` varchar(40) DEFAULT NULL,
  `FUNCIONARIO_DATAADMISSAO` date DEFAULT NULL,
  `FUNCIONARIO_FUNCAO` varchar(50) DEFAULT NULL,
  `FUNCIONARIO_CPF` varchar(11) DEFAULT NULL,
  `FUNCIONARIO_LOGIN` varchar(15) DEFAULT NULL,
  `FUNCIONARIO_SENHA` varchar(15) DEFAULT NULL,
  `EMPRESA_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_CODIGO`),
  KEY `FK_FUNCIONARIO_EMPRESA_CODIGO` (`EMPRESA_CODIGO`),
  CONSTRAINT `FK_FUNCIONARIO_EMPRESA_CODIGO` FOREIGN KEY (`EMPRESA_CODIGO`) REFERENCES `empresa` (`EMPRESA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.funcionario: ~0 rows (approximately)
/*!40000 ALTER TABLE `funcionario` DISABLE KEYS */;
/*!40000 ALTER TABLE `funcionario` ENABLE KEYS */;


-- Dumping structure for table locadora.genero
CREATE TABLE IF NOT EXISTS `genero` (
  `GENERO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `GENERO_DECRICAO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`GENERO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.genero: ~0 rows (approximately)
/*!40000 ALTER TABLE `genero` DISABLE KEYS */;
/*!40000 ALTER TABLE `genero` ENABLE KEYS */;


-- Dumping structure for table locadora.itens_midia
CREATE TABLE IF NOT EXISTS `itens_midia` (
  `ITENS_MIDIA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `ITENS_MIDIA_DESCRICAO` varchar(50) DEFAULT NULL,
  `EMPRESTIMO_CODIGO` int(11) NOT NULL,
  `MIDIAS_CODIGO` int(11) NOT NULL,
  `DESCARTE_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`ITENS_MIDIA_CODIGO`),
  KEY `FK_EMPRESTIMO_CODIGO` (`EMPRESTIMO_CODIGO`),
  KEY `FK_ITENS_MIDIA_MIDIAS_CODIGO` (`MIDIAS_CODIGO`),
  KEY `FK_ITENS_MIDIA_DESCARTE_CODIGO` (`DESCARTE_CODIGO`),
  CONSTRAINT `FK_EMPRESTIMO_CODIGO` FOREIGN KEY (`EMPRESTIMO_CODIGO`) REFERENCES `emprestimo` (`EMPRESTIMO_CODIGO`),
  CONSTRAINT `FK_ITENS_MIDIA_DESCARTE_CODIGO` FOREIGN KEY (`DESCARTE_CODIGO`) REFERENCES `descarte` (`DESCARTE_CODIGO`),
  CONSTRAINT `FK_ITENS_MIDIA_MIDIAS_CODIGO` FOREIGN KEY (`MIDIAS_CODIGO`) REFERENCES `midias` (`MIDIAS_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.itens_midia: ~0 rows (approximately)
/*!40000 ALTER TABLE `itens_midia` DISABLE KEYS */;
/*!40000 ALTER TABLE `itens_midia` ENABLE KEYS */;


-- Dumping structure for table locadora.midias
CREATE TABLE IF NOT EXISTS `midias` (
  `MIDIAS_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `MIDIAS_NOME` varchar(40) DEFAULT NULL,
  `MIDIAS_DIRETOR` varchar(40) DEFAULT NULL,
  `MIDIAS_ATORES` blob,
  `MIDIAS_SINOPSE` blob,
  `MIDIAS_IMAGENS` int(11) DEFAULT NULL,
  `MIDIAS_ANO_LANCAMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `GENERO_CODIGO` int(11) NOT NULL,
  `CLASSIFICACAO_CODIGO` int(11) NOT NULL,
  `CATEGORIA_MIDIA_CODIGO` int(11) NOT NULL,
  `MIDIA_COPIAS` int(11) DEFAULT NULL,
  PRIMARY KEY (`MIDIAS_CODIGO`),
  KEY `FK_GENERO_CODIGO` (`GENERO_CODIGO`),
  KEY `FK_CLASSIFICACAO_CODIGO` (`CLASSIFICACAO_CODIGO`),
  KEY `FK_CATEGORIA_MIDIA_CODIGO` (`CATEGORIA_MIDIA_CODIGO`),
  CONSTRAINT `FK_CATEGORIA_MIDIA_CODIGO` FOREIGN KEY (`CATEGORIA_MIDIA_CODIGO`) REFERENCES `categoria_midia` (`CATEGORIA_MIDIA_CODIGO`),
  CONSTRAINT `FK_CLASSIFICACAO_CODIGO` FOREIGN KEY (`CLASSIFICACAO_CODIGO`) REFERENCES `classificacao` (`CLASSIFICACAO_CODIGO`),
  CONSTRAINT `FK_GENERO_CODIGO` FOREIGN KEY (`GENERO_CODIGO`) REFERENCES `genero` (`GENERO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.midias: ~0 rows (approximately)
/*!40000 ALTER TABLE `midias` DISABLE KEYS */;
/*!40000 ALTER TABLE `midias` ENABLE KEYS */;


-- Dumping structure for table locadora.movimentacao
CREATE TABLE IF NOT EXISTS `movimentacao` (
  `MOVIMENTACAO_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `MOVIMENTACAO_DESCRICAO` varchar(255) DEFAULT NULL,
  `FUNCIONARIO_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`MOVIMENTACAO_CODIGO`),
  KEY `FK_MOVIMENTACAO_FUNCIONARIO_CODIGO` (`FUNCIONARIO_CODIGO`),
  CONSTRAINT `FK_MOVIMENTACAO_FUNCIONARIO_CODIGO` FOREIGN KEY (`FUNCIONARIO_CODIGO`) REFERENCES `funcionario` (`FUNCIONARIO_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.movimentacao: ~0 rows (approximately)
/*!40000 ALTER TABLE `movimentacao` DISABLE KEYS */;
/*!40000 ALTER TABLE `movimentacao` ENABLE KEYS */;


-- Dumping structure for table locadora.tipo_midia
CREATE TABLE IF NOT EXISTS `tipo_midia` (
  `TIPO_MIDIA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_MIDIA_VALOR` decimal(10,2) DEFAULT NULL,
  `TIPO_MIDIA_QTD_DIAS` int(11) DEFAULT NULL,
  `CATEGORIA_MIDIA_CODIGO` int(11) NOT NULL,
  PRIMARY KEY (`TIPO_MIDIA_CODIGO`),
  KEY `FK_TIPO_MIDIA_CATEGORIA_MIDIA_CODIGO` (`CATEGORIA_MIDIA_CODIGO`),
  CONSTRAINT `FK_TIPO_MIDIA_CATEGORIA_MIDIA_CODIGO` FOREIGN KEY (`CATEGORIA_MIDIA_CODIGO`) REFERENCES `categoria_midia` (`CATEGORIA_MIDIA_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table locadora.tipo_midia: ~0 rows (approximately)
/*!40000 ALTER TABLE `tipo_midia` DISABLE KEYS */;
/*!40000 ALTER TABLE `tipo_midia` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
